# Generated by Django 6.0.7 on 2026-07-19 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VideoJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='uploads/')),
                ('status', models.CharField(choices=[('Uploaded', 'Uploaded'), ('Processing', 'Processing'), ('Completed', 'Completed'), ('Failed', 'Failed')], default='Uploaded', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('audio_path', models.CharField(blank=True, max_length=255)),
                ('transcript', models.TextField(blank=True)),
                ('summary', models.TextField(blank=True)),
            ],
        ),
    ]
