# Generated by Django 6.0.7 on 2026-07-20 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('converter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videojob',
            name='audio_path',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='videojob',
            name='status',
            field=models.CharField(choices=[('Uploaded', 'Uploaded'), ('Extracting Audio', 'Extracting Audio'), ('Transcribing', 'Transcribing'), ('Summarizing', 'Summarizing'), ('Completed', 'Completed')], default='Uploaded', max_length=50),
        ),
    ]
