# Generated by Django 6.0.7 on 2026-07-20 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('converter', '0002_alter_videojob_audio_path_alter_videojob_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='videojob',
            name='audio_status',
            field=models.CharField(default='Waiting', max_length=50),
        ),
        migrations.AddField(
            model_name='videojob',
            name='hook_status',
            field=models.CharField(default='Waiting', max_length=50),
        ),
        migrations.AddField(
            model_name='videojob',
            name='seo_status',
            field=models.CharField(default='Waiting', max_length=50),
        ),
        migrations.AddField(
            model_name='videojob',
            name='speech_status',
            field=models.CharField(default='Waiting', max_length=50),
        ),
        migrations.AddField(
            model_name='videojob',
            name='summary_status',
            field=models.CharField(default='Waiting', max_length=50),
        ),
    ]
